//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dx.misv.passwordbot.app.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dx.misv.passwordbot.app.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complex
        ///compound
        ///difficult
        ///analyzable
        ///Byzantine
        ///colonial
        ///complicated
        ///composite
        ///compound
        ///convoluted
        ///daedal
        ///decomposable
        ///Gordian
        ///interlacing
        ///interlinking
        ///interlocking
        ///interwoven
        ///intricate
        ///involved
        ///knotty
        ///labyrinthian
        ///labyrinthine
        ///mazy
        ///multifactorial
        ///multiplex
        ///tangled
        ///thickening
        ///tortuous.
        /// </summary>
        internal static string complex {
            get {
                return ResourceManager.GetString("complex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elementary
        ///uncomplicated
        ///unproblematic
        ///childlike
        ///wide-eyed
        ///round-eyed
        ///dewy-eyed
        ///dim-witted
        ///simple-minded
        ///unsubdivided
        ///bare
        ///half-witted
        ///mere
        ///simple
        ///unsubdivided
        ///easy
        ///plain
        ///smooth
        ///uncomplicated
        ///acerate
        ///acerose
        ///acicular
        ///acuminate
        ///apiculate
        ///arrow-shaped
        ///bladelike
        ///caudate
        ///cordate
        ///cordiform
        ///cuneate
        ///deltoid
        ///dolabrate
        ///dolabriform
        ///easy
        ///elliptic
        ///elongate
        ///ensiform
        ///hastate
        ///lancelike
        ///lanceolate
        ///linear
        ///lyrate
        ///naif
        ///naive
        ///needled
        ///oblanceolate
        ///oblong
        ///obovate
        ///obtuse
        ///orbicular        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string simple {
            get {
                return ResourceManager.GetString("simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strong
        ///potent
        ///stiff
        ///impregnable
        ///inviolable
        ///secure
        ///unassailable
        ///unattackable
        ///solid
        ///substantial
        ///hard
        ///warm
        ///firm
        ///effective
        ///effectual
        ///efficacious
        ///fertile
        ///powerful
        ///robust
        ///rugged
        ///tough
        ///toughened
        ///stiff
        ///hard
        ///alcoholic
        ///beardown
        ///beefed-up
        ///brawny
        ///bullnecked
        ///bullocky
        ///equipotent
        ///forceful
        ///fortified
        ///fresh
        ///hefty
        ///industrial-strength
        ///intense
        ///invulnerable
        ///ironlike
        ///irregular
        ///knock-down
        ///knockout
        ///multipotent
        ///muscular
        ///noticeable
        ///powerful
        ///reinforced
        ///robust
        ///severe
        ///sinewy
        ///sound
        ///stren [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string strong {
            get {
                return ResourceManager.GetString("strong", resourceCulture);
            }
        }
    }
}
